#! /bin/sh

sxhkd & > /tmp/sxhkd.log 2>&1 &
picom --config /home/jan/.config/picom/picom.conf &
xborders -c /home/jan/.config/xborders/config.json &
feh --bg-scale $(cat /home/jan/Pictures/wallpapers/selected)
polybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap           5
bspc config border_width         0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

exec bspwm
