require("config.lazy")
require("config.remap")
require("config.lsp")
require("config.set")
require("config.harpoon")
require("config.lualine")
require("config.autocommand")
require("config.macro")

vim.cmd([[colorscheme tokyonight]])
